# Gripper Configuration
config_vacuum_gripper:
  vacuum_gripper_model_name: "scara_gripper"
  vacuum_gripper_link_name: "vacuum_gripper_link"
  
  attachable_object_link_name: "link"

  attachable_object_prefix: "package"
  attachable_object_delimiter: "n"
  logical_camera_topic_name: "/scara/vacuum_gripper/logical_camera/sociopulator"
